# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0004_auto_20180227_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressrecord',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.0.2.30', unique=True, verbose_name='IP address'),
        ),
    ]
